csharp/aspdotnet2/LoginReg/Models/BaseEntity.cs
namespace LoginReg.Models{

    public abstract class BaseEntity{
        
    }

}

csharp/aspdotnet2/LoginReg/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace LoginReg.Models {

    public class User : BaseEntity {
        
        [Key]
        public int id {get; set;}

        [Display(Name = "First Name")]
        [RegularExpression(@"^[a-zA-Z''-'\s]+$" , ErrorMessage = "#s or special  Characters are not allowed.")]
        [RequiredAttribute(ErrorMessage = "First Name is required")]
        [MinLengthAttribute(2)]
        public string FirstName {get; set;}
        
        [Display(Name = "Last Name")]
        [RegularExpression(@"^[a-zA-Z''-'\s]+$" , ErrorMessage = "#s or special Characters are not allowed.")]
        [RequiredAttribute(ErrorMessage = "Last Name is required")]
        [MinLengthAttribute(2)]
        public string LastName {get; set;}

        [RequiredAttribute]
        [EmailAddressAttribute]
        public string Email {get; set;}

        [RequiredAttribute]
        [MinLengthAttribute(8)]
        [DataType(DataType.Password)]
        public string Password {get; set;}

        [Display(Name = "Confrim Password")]
        [RequiredAttribute()]
        [CompareAttribute("Password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword {get; set;}



    }
}

csharp/aspdotnet2/LoginReg/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using DapperApp.Factory;
using LoginReg.Models;
using Microsoft.AspNetCore.Mvc;

namespace LoginReg.Controllers
{
    public class LoginRegController : Controller
    {

        private readonly UserFactory userFactory;
        public LoginRegController()
        {
            //Instantiate a UserFactory object that is immutable (READONLY)
            //This establishes the initial DB connection for us.
            userFactory = new UserFactory();
        }
        // GET: /Home/
        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            return View();
        }
       
        [HttpPost]
        [Route("register")]
        public IActionResult Index(User user)
        {
            if(ModelState.IsValid){
                userFactory.Add(user);
                return RedirectToAction("Success");
            }

            return View(user);

        }

        [HttpPost]
        [Route("login")]
        public IActionResult Login(User user)
        {
            if((user.Email != null && user.Email.Length > 0 ) && (user.Password !=null && user.Password.Length > 0) ){
                User loginUser = userFactory.FindByEmail(user.Email);                
                if(loginUser != null && loginUser.Password == user.Password)
                    return RedirectToAction("Success");              
            }
            
            return View("Index");

        }
       
        [HttpGet]
        [Route("success")]
        public IActionResult Success()
        {
           return View();
        }
    }
}

csharp/aspdotnet2/LoginReg/Views/LoginReg/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model LoginReg.Models.User
 
<form asp-controller="LoginReg" asp-action="Index" method="post">
    <div class=row>
            <h2 class="col-xs-12 col-md-12  col-md-offset-2 ">Register</h2>
    </div>
    <label asp-for="FirstName" class="col-xs-12 col-md-2  "></label>
    <input asp-for="FirstName" class="col-xs-12 col-md-2"/><br><br>


    <label asp-for="LastName" class="col-xs-12 col-md-2"></label>
    <input asp-for="LastName" class="col-xs-12 col-md-3"/><br><br>


    <label asp-for="Email" class="col-xs-12 col-md-2"></label>
    <input asp-for="Email" class="col-xs-12 col-md-3"/><br><br>

    <label asp-for="Password" class="col-xs-12 col-md-2"></label>
    <input asp-for="Password" class="col-xs-12 col-md-2"/><br><br>
    <label asp-for="ConfirmPassword" class="col-xs-12 col-md-2"></label>
    <input asp-for="ConfirmPassword"class="col-xs-12 col-md-2"/><br><br>
    <button type="submit">Register</button>   
    <div asp-validation-summary="All"></div>

   
</form>
<br>

<br><br>
<form asp-controller="LoginReg" asp-action="Login" method="post">
     <div class=row>
            <h2 class="col-xs-12 col-md-12  col-md-offset-2 ">Login</h2>
    </div>
    <span asp-validation-for="Email"></span>
    <label asp-for="Email" class="col-xs-12 col-md-2"></label>
    <input asp-for="Email" class="col-xs-12 col-md-3"/><br><br>
    <span asp-validation-for="Password"></span>
    <label asp-for="Password" class="col-xs-12 col-md-2"></label>
    <input asp-for="Password" class="col-xs-12 col-md-2"/><br><br>
    
    <button type="submit">Login</button>
</form>


<!--namespace YourNamespace.Controllers
{
    [HttpGet]
    [Route("RouteName/{example}")]
    public IActionResult Method(string example)
    {
        //Code body
    }
}
Copy
And we can link to such a route with an anchor tag like so:

SomeView.cshtml
<a asp-controller="Your" asp-action="Method" asp-route-example="PassMeThroughUrl">link with parameter</a>-->